version: "3.7"
services:
  composer:
    # 初回起動時の composer の実施用
    # https://hub.docker.com/r/prooph/composer
    # https://github.com/prooph/docker-files
    image: prooph/composer:7.4
    command: update
    volumes:
      - ./:/app
    restart: "no"
  web:
    build:
      context: ./.container/web
    ports:
      - 80:80
      - 443:443
    privileged: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
      - ./.container/web/apache.conf:/etc/httpd/conf/httpd.conf
      - cert:/etc/ssl/private
    restart: always
    depends_on:
      - "composer"
volumes:
  cert:
